<?php
if ( ! defined( 'ABSPATH' ) ) :
    exit; // Exit if accessed directly
endif;

function tt_vc_template_home_corporate( $data ) {
	$template                   = array();
	$template[ 'name' ]         = esc_html__( 'Home Corporate', 'materialize');
	$template[ 'custom_class' ] = 'tt_vc_template_home_corporate';

	ob_start();
	?>[vc_row][vc_column][rev_slider_vc alias="corporate-slider"][/vc_column][/vc_row][vc_row css=".vc_custom_1461537055026{padding-top: 120px !important;padding-bottom: 100px !important;}"][vc_column width="1/2"][vc_custom_heading text="Company's Overview" font_container="tag:h2|font_size:35px|text_align:left|color:%23ff2a40|line_height:30px" use_theme_fonts="yes" css=".vc_custom_1460106815916{margin-bottom: 30px !important;}"][vc_column_text css=".vc_custom_1461537115210{margin-bottom: 43px !important;}"]Messenger bag gentrify pitchfork tattooed craft beer iphone skateboard locavore carles etsy viny Photo booth beard raw denim letterpress vegan messenger bag stumptown. American apparel have a terry richardson vinyl chambray. American apparel have a terry richardson vinyl chambray.[/vc_column_text][vc_btn title="Learn More" style="classic" align="left" color="theme_primary_color"][/vc_column][vc_column width="1/2"][vc_video link="https://player.vimeo.com/video/23534361?title=0&amp;byline=0&amp;portrait=0"][/vc_column][/vc_row][vc_row css=".vc_custom_1460529049797{padding-top: 100px !important;padding-bottom: 95px !important;background-color: #ff2a40 !important;}"][vc_column][tt_section_title title_alignment="text-center" title_color_option="custom-color" description_color_option="custom-color" title="What Make Us Awesome" css=".vc_custom_1460112502341{margin-bottom: 80px !important;}" title_color="#ffffff" description_color="#ffffff"]Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur
magni dolores eos qui ratione voluptatem sequi nesciunt.[/tt_section_title][vc_row_inner][vc_column_inner][tt_icon_blocks][tt_icon_block show_icon="yes" icon_style="icon-circle" icon_type="flat-icon" icon_position="icon-position-center" icon_color_option="custom-color" icon_hover_bg_color="icon-hover-white" title_color_option="custom-color" custom_link="yes" title="Innovation" link="url:%23||" icon_color="#ffffff" title_color="#ffffff" flat_icon="flaticon-light92"]<span style="color: #ffffff;">Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores.</span>[/tt_icon_block][tt_icon_block show_icon="yes" icon_style="icon-circle" icon_type="flat-icon" icon_position="icon-position-center" icon_color_option="custom-color" icon_hover_bg_color="icon-hover-white" title_color_option="custom-color" custom_link="yes" title="Productive" link="url:%23||" icon_color="#ffffff" title_color="#ffffff" flat_icon="flaticon-cup55"]<span style="color: #ffffff;">Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores.</span>[/tt_icon_block][tt_icon_block show_icon="yes" icon_style="icon-circle" icon_type="flat-icon" icon_position="icon-position-center" icon_color_option="custom-color" icon_hover_bg_color="icon-hover-white" title_color_option="custom-color" custom_link="yes" title="Learner Mind" link="url:%23||" icon_color="#ffffff" title_color="#ffffff" flat_icon="flaticon-find5"]<span style="color: #ffffff;">Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores.</span>[/tt_icon_block][/tt_icon_blocks][/vc_column_inner][/vc_row_inner][/vc_column][/vc_row][vc_row css=".vc_custom_1460529249775{margin-top: 100px !important;border-bottom-width: 1px !important;padding-bottom: 100px !important;border-bottom-color: #d2d2d2 !important;border-bottom-style: solid !important;}"][vc_column][tt_section_title title_alignment="text-center" title_color_option="theme-color" title="Our Studio's Gallery." css=".vc_custom_1461541713260{padding-bottom: 60px !important;}"]Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur
magni dolores eos qui ratione voluptatem sequi nesciunt.[/tt_section_title][tt_gallery gallery_type="image-gallery" images="4077,4078,4079,4084,4081,4082"][/vc_column][/vc_row][vc_row section_content_width="container-fullwidth" css=".vc_custom_1460529785726{border-bottom-width: 1px !important;padding-top: 100px !important;padding-bottom: 48px !important;background-color: #fafafa !important;border-bottom-color: #d2d2d2 !important;border-bottom-style: solid !important;}"][vc_column][tt_section_title title_alignment="text-center" title_color_option="theme-color" title="Some Of Our Works" css=".vc_custom_1461541906620{padding-bottom: 15px !important;}"]Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur
magni dolores eos qui ratione voluptatem sequi nesciunt.[/tt_section_title][tt_work_carousel images="2401,2400,3623"][vc_btn title="View More" style="classic" size="lg" align="center" color="theme_primary_color" css=".vc_custom_1460118758350{padding-top: 80px !important;}"][/vc_column][/vc_row][vc_row css=".vc_custom_1460529927482{margin-top: 100px !important;margin-bottom: 100px !important;}"][vc_column][tt_section_title title_alignment="text-center" title_color_option="theme-color" title="Our Clients Love Us!" css=".vc_custom_1461541667429{padding-bottom: 60px !important;}"]Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur
magni dolores eos qui ratione voluptatem sequi nesciunt.[/tt_section_title][tt_testimonial carousel_type="flex-carousel" testimonial_info="%5B%7B%22photo_option%22%3A%22yes%22%2C%22client_image%22%3A%222734%22%2C%22client_name%22%3A%22Jhon%20Doe%22%2C%22client_org%22%3A%22Techmart.%20Bd%22%2C%22content%22%3A%22Nemo%20enim%20ipsam%20voluptatem%20quia%20voluptas%20sit%20aspernatur%20aut%20odit%20aut%20fugit%2C%20sed%20quia%20consequuntur%20magni%20dolores%20eos%20qui%20ratione%20voluptatem%20sequi%20nesciunt%20magni%20dolores%20eos%20qui%20ratione%20voluptatem.%22%7D%2C%7B%22photo_option%22%3A%22yes%22%2C%22client_image%22%3A%222732%22%2C%22client_name%22%3A%22Vernon%20Royle%22%2C%22client_org%22%3A%22Themelab%22%2C%22content%22%3A%22Nemo%20enim%20ipsam%20voluptatem%20quia%20voluptas%20sit%20aspernatur%20aut%20odit%20aut%20fugit%2C%20sed%20quia%20consequuntur%20magni%20dolores%20eos%20qui%20ratione%20voluptatem%20sequi%20nesciunt%20magni%20dolores%20eos%20qui%20ratione%20voluptatem.%22%7D%2C%7B%22photo_option%22%3A%22yes%22%2C%22client_image%22%3A%222733%22%2C%22client_name%22%3A%22Billy%20Barnes%22%2C%22client_org%22%3A%22Themovation%22%2C%22content%22%3A%22Nemo%20enim%20ipsam%20voluptatem%20quia%20voluptas%20sit%20aspernatur%20aut%20odit%20aut%20fugit%2C%20sed%20quia%20consequuntur%20magni%20dolores%20eos%20qui%20ratione%20voluptatem%20sequi%20nesciunt%20magni%20dolores%20eos%20qui%20ratione%20voluptatem.%22%7D%5D"][/vc_column][/vc_row][vc_row css=".vc_custom_1460271582968{margin-bottom: 110px !important;}"][vc_column][tt_call_to_action title_color_option="custom-color" content_alignment="text-left" button_visibility="visible" button_style="btn-outline" button_size="btn-md" button_position="button-right" title="Start Building Your Project With 69Studio!" button_text="Contact Us" button_link="url:%23||" css=".vc_custom_1461543164633{padding-top: 40px !important;padding-right: 40px !important;padding-bottom: 20px !important;padding-left: 40px !important;background-color: #ff2a40 !important;}" title_color="#ffffff" subtitle_font_size="18px" title_font_size="25px"]<span style="color: #ffffff;">We truly care about our users and our product.</span>[/tt_call_to_action][/vc_column][/vc_row]
	<?php
	$template[ 'content' ] = ob_get_clean();
	array_unshift( $data, $template );
	return $data;
}
add_filter( 'vc_load_default_templates', 'tt_vc_template_home_corporate' );