<?php
if ( ! defined( 'ABSPATH' ) ) :
    exit; // Exit if accessed directly
endif;

function tt_vc_template_onepage_app_landing( $data ) {
	$template                   = array();
	$template[ 'name' ]         = esc_html__( 'OnePage App Landing', 'materialize');
	$template[ 'custom_class' ] = 'tt_vc_template_onepage_app_landing';

	ob_start();
	?>[vc_row][vc_column css=".vc_custom_1461483141132{margin-bottom: -35px !important;}"][rev_slider_vc alias="app-landing-page"][/vc_column][/vc_row][vc_row css=".vc_custom_1462039458326{padding-top: 130px !important;}" el_id="features"][vc_column][tt_section_title title_alignment="text-center" title_color_option="theme-color" title="App Features" css=".vc_custom_1461391412269{margin-bottom: 80px !important;}"]Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur
magni dolores eos qui ratione voluptatem sequi nesciunt.[/tt_section_title][vc_row_inner css=".vc_custom_1461393679623{padding-bottom: 80px !important;}"][vc_column_inner width="7/12"][tt_icon_blocks grid_column="12"][tt_icon_block show_icon="yes" icon_style="icon-round" icon_type="flat-icon" icon_position="icon-position-left" icon_color_option="theme-color" icon_hover_bg_color="icon-hover-default" flat_icon="flaticon-certificate3" title="Modern Design" css=".vc_custom_1461392633001{margin-bottom: 30px !important;}"]Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nulla similique eaque aliquam quia, facilis tempore natus dolor sit amet, consectetur adipisicing elit.[/tt_icon_block][tt_icon_block show_icon="yes" icon_style="icon-round" icon_type="flat-icon" icon_position="icon-position-left" icon_color_option="theme-color" icon_hover_bg_color="icon-hover-default" flat_icon="flaticon-levels1" title="Easy To Customize" css=".vc_custom_1461392564151{margin-bottom: 30px !important;}"]Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nulla similique eaque aliquam quia, facilis tempore natus.[/tt_icon_block][tt_icon_block show_icon="yes" icon_style="icon-round" icon_type="flat-icon" icon_position="icon-position-left" icon_color_option="theme-color" icon_hover_bg_color="icon-hover-default" flat_icon="flaticon-bulb19" title="Different Versions"]Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nulla similique eaque aliquam quia, facilis tempore natus.[/tt_icon_block][/tt_icon_blocks][/vc_column_inner][vc_column_inner width="5/12"][vc_single_image image="3864" img_size="full" alignment="center" css_animation="right-to-left" css=".vc_custom_1462039060472{margin-bottom: 0px !important;}"][/vc_column_inner][/vc_row_inner][/vc_column][/vc_row][vc_row css=".vc_custom_1462039788765{border-top-width: 1px !important;border-bottom-width: 1px !important;padding-top: 100px !important;padding-bottom: 100px !important;background-color: #fafafa !important;border-top-color: #f2f2f2 !important;border-top-style: solid !important;border-bottom-color: #f2f2f2 !important;border-bottom-style: solid !important;}" el_id="how-it-works"][vc_column width="5/12"][vc_single_image image="3844" img_size="full" alignment="center" css_animation="left-to-right" css=".vc_custom_1461774286196{margin-bottom: 0px !important;}"][/vc_column][vc_column width="1/2" offset="vc_col-sm-offset-1"][vc_column_text css_animation="right-to-left"]
<h2 class="section-title theme-color">How It Works?</h2>
Continually underwhelm visionary models with cross-unit synergy. Uniquely leverage other's premium convergence before progressive data. Proactively monetize visionary models.
<ul class="check-circle-list">
 	<li><i class="fa fa-check-circle"></i> Uniquely disseminate economically sound bandwidth</li>
 	<li><i class="fa fa-check-circle"></i> Quickly reinvent cross functional infrastructures</li>
 	<li><i class="fa fa-check-circle"></i> High standards in niche markets capital istinctively</li>
 	<li><i class="fa fa-check-circle"></i> Intellectual capital fluorcently foster business</li>
</ul>
[/vc_column_text][/vc_column][/vc_row][vc_row css=".vc_custom_1462039842933{padding-top: 100px !important;padding-bottom: 100px !important;background-position: 0 0 !important;background-repeat: repeat !important;}" el_id="portfolio"][vc_column][tt_section_title title_alignment="text-center" title_color_option="theme-color" title="App Screenshots" css=".vc_custom_1461393896689{margin-bottom: 80px !important;}"]Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur
magni dolores eos qui ratione voluptatem sequi nesciunt.[/tt_section_title][vc_media_grid element_width="3" grid_id="vc_gid:1462044969471-96b24cfa-0113-3" include="3847,3848,3849,3850"][/vc_column][/vc_row][vc_row parallax="content-moving" parallax_image="2711" apply_overlay="true" overlay_color="rgba(0,0,0,0.5)"][vc_column][tt_counts][tt_count show_icon="yes" icon_type="flat-icon" grid_class="col-sm-4" counted_number="1500" subtitle="Happy Users" flat_icon="flaticon-cup55"][/tt_count][tt_count show_icon="yes" icon_type="flat-icon" highlighted="selected" grid_class="col-sm-4" counted_number="2100" subtitle="Downloads" flat_icon="flaticon-game84"][/tt_count][tt_count show_icon="yes" icon_type="flat-icon" grid_class="col-sm-4" counted_number="1700" subtitle="Premium Users" flat_icon="flaticon-gift84"][/tt_count][/tt_counts][/vc_column][/vc_row][vc_row css=".vc_custom_1462039866730{padding-top: 100px !important;padding-bottom: 100px !important;background-position: center !important;background-repeat: no-repeat !important;background-size: cover !important;}" el_id="about"][vc_column width="1/2"][vc_column_text css_animation="left-to-right"]
<h2 class="section-title theme-color">Video Introduction</h2>
Messenger bag gentrify pitchfork tattooed craft beer iphone skateboard locavore carles etsy viny Photo booth beard raw denim letterpress vegan messenger bag stumptown. American apparel have a terry richardson vinyl chambray.

Photo bag gentrify pitchfork tattooed craft beer iphone skateboard locavore carles etsy viny Photo booth beard raw denim letterpress vegan messenger bag stumptown. American apparel have a terry richardson vinyl chambray. Messenger bag gentrify pitchfork tattooed craft beer iphone skateboard locavore carles etsy viny Photo booth beard raw denim letterpress vegan messenger bag stumptown.[/vc_column_text][/vc_column][vc_column width="1/2"][vc_video link="https://www.youtube.com/watch?v=_0qa4chrTAY"][/vc_column][/vc_row][vc_row css=".vc_custom_1462045092314{padding-top: 100px !important;padding-bottom: 100px !important;background-image: url(http://trendytheme.net/demo2/wp/69/onepage/app-landing/wp-content/uploads/sites/2/2016/04/subcribe-bg1.jpg?id=3875) !important;background-position: center !important;background-repeat: no-repeat !important;background-size: cover !important;}" apply_overlay="true" overlay_color="rgba(0,0,0,0.5)"][vc_column][vc_column_text css_animation="bottom-to-top"]
<h2 style="text-align: center;"><span style="color: #ffffff;">Newsletter Subscribe</span></h2>
[/vc_column_text][tt_newsletter][/vc_column][/vc_row][vc_row css=".vc_custom_1462039885008{padding-top: 100px !important;padding-bottom: 100px !important;}" el_id="clients"][vc_column][tt_section_title title_alignment="text-center" title_color_option="theme-color" title="Our Happy Clients" css=".vc_custom_1461397886154{margin-bottom: 80px !important;}"]Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur[/tt_section_title][tt_partners images="3854,3855,3856,3857,3858,3859,3860,3861"][/vc_column][/vc_row]
	<?php
	$template[ 'content' ] = ob_get_clean();
	array_unshift( $data, $template );
	return $data;
}
add_filter( 'vc_load_default_templates', 'tt_vc_template_onepage_app_landing' );